services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm install && npm run build
    startCommand: cd dist && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: GMAIL_RECEIVER
        sync: false 