services:
  - type: web
    name: portfolio
    env: node
    buildCommand: |
      npm install
      npm install --production=false
      npm run build
      cd server && npm install
    startCommand: cd dist && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: GMAIL_RECEIVER
        sync: false 