services:
  - type: web
    name: portfolio
    env: node
    buildCommand: |
      # Install all dependencies including dev dependencies
      npm install
      # Install Vite and React plugin explicitly
      npm install vite @vitejs/plugin-react @replit/vite-plugin-runtime-error-modal @replit/vite-plugin-cartographer --save-dev
      # Build the application
      npm run build
      # Install server dependencies
      cd server && npm install
    startCommand: cd dist && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: GMAIL_RECEIVER
        sync: false 